### ISSUE TITLE
Update embedded Operator

### ISSUE THREAD

**Issue by mrhillsman** [IBM/ibm-metering-operator#94]
Hi,

I work on the Red Hat Operator Enablement team which works on existing and new operators embedded with OpenShift or publicly available via OperatorHub.io.

Currently, the IBM Metering Operator is missing quite a bit of documentation/information. Please see the attached image to verify. If no longer in use the operator should be removed. At a minimum, the CSV needs to be updated to provide more information.

Thank you for your time and attention to this matter,

Melvin Hillsman

![OperatorHub · Red Hat OpenShift Container Platform](https://user-images.githubusercontent.com/3989695/84809364-96201f00-afcf-11ea-92f6-622abdfdb2b3.png)

**Comment by sgrube** [comment]
@mrhillsman We have been trying to unpublish this operator, but so far have not been successful.  Do you have instructions for how to unpublish?

**Comment by mrhillsman** [comment]
@sgrube Apologies for the late reply I think I had a cached version of this issue without your comment showing up. You will need to open a ticket in the connect portal - where a certified operator is published - and get assistance from the team on the backend.

**Comment by mrhillsman** [comment]
@sgrube did you need any assistance with this still?

**Comment by sgrube** [comment]
@mrhillsman The operator has been unpublished and removed now.  I'm going to close the issue.
